/**
 * ============================================================================
 * CHAT ROOM PAGE - [sessionId].jsx
 * ============================================================================
 * 
 * PURPOSE:
 * The real-time chat room where two matched users can communicate.
 * This is a dynamic route that receives the sessionId from the URL.
 * 
 * FEATURES:
 * - Real-time messaging with Socket.io
 * - Typing indicators
 * - Multiple chat themes (Light, Dark, Ocean, Sunset, Forest)
 * - Report user functionality
 * - "Find Next" to leave and find a new match
 * - Auto-scroll to newest messages
 * - Partner disconnect detection
 * 
 * SOCKET EVENTS:
 * - Emits: auth:register, chat:send, chat:typing, chat:leave, chat:report
 * - Listens: chat:message, chat:typing, chat:partnerLeft
 * 
 * DYNAMIC ROUTING:
 * URL pattern: /chat/[sessionId]
 * The sessionId is generated by the server when a match is found.
 * 
 * STATE:
 * - messages: Array of message objects { id, content, sender, timestamp, isOwn }
 * - inputValue: Current message being typed
 * - partnerInfo: Partner's nickname and bio
 * - isPartnerTyping: Whether partner is currently typing
 * - chatEnded: Whether chat session has ended
 * - currentTheme: Active chat theme
 * 
 * ============================================================================
 */

import { useSocket } from 'context/SocketContext';
import { useRouter } from 'next/router';
import { useEffect, useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { appConfig, animations } from 'config/config';
import { getUserData } from 'utils/deviceId';

// ============================================================================
// CHAT THEMES CONFIGURATION
// ============================================================================
// Each theme defines colors for different UI elements
// Users can switch themes via the palette button in the header
// All themes are light-based with subtle background patterns (like WhatsApp)

const chatThemes = {
  // Classic light theme - clean and minimal
  classic: {
    name: 'Classic',
    icon: '⬜',
    bg: 'bg-[#f0f2f5]',                                // WhatsApp-style light grey
    chatBg: 'bg-[#efeae2]',                            // Warm beige chat background
    pattern: 'chat-pattern-classic',                    // Subtle doodle pattern
    ownMsg: 'bg-[#d9fdd3] text-grey-900',              // WhatsApp green bubble
    partnerMsg: 'bg-white text-grey-800 shadow-sm',    // White bubble
    headerBg: 'bg-white/95 backdrop-blur-lg border-b border-grey-200',
    inputBg: 'bg-white',
    accent: '#25D366',                                  // WhatsApp green
  },
  
  // Ocean blue theme - calm and serene
  ocean: {
    name: 'Ocean',
    icon: '🌊',
    bg: 'bg-gradient-to-br from-sky-50 to-blue-100',
    chatBg: 'bg-sky-50/80',
    pattern: 'chat-pattern-waves',
    ownMsg: 'bg-blue-500 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-blue-100',
    inputBg: 'bg-white',
    accent: '#0ea5e9',
  },
  
  // Lavender theme - soft and dreamy
  lavender: {
    name: 'Lavender',
    icon: '💜',
    bg: 'bg-gradient-to-br from-purple-50 to-violet-100',
    chatBg: 'bg-purple-50/70',
    pattern: 'chat-pattern-dots',
    ownMsg: 'bg-violet-500 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-purple-100',
    inputBg: 'bg-white',
    accent: '#8b5cf6',
  },
  
  // Mint theme - fresh and clean
  mint: {
    name: 'Mint',
    icon: '🍃',
    bg: 'bg-gradient-to-br from-emerald-50 to-teal-100',
    chatBg: 'bg-emerald-50/70',
    pattern: 'chat-pattern-leaves',
    ownMsg: 'bg-emerald-500 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-emerald-100',
    inputBg: 'bg-white',
    accent: '#10b981',
  },
  
  // Peach theme - warm and friendly
  peach: {
    name: 'Peach',
    icon: '🍑',
    bg: 'bg-gradient-to-br from-orange-50 to-amber-100',
    chatBg: 'bg-orange-50/70',
    pattern: 'chat-pattern-circles',
    ownMsg: 'bg-gradient-to-r from-orange-400 to-amber-400 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-orange-100',
    inputBg: 'bg-white',
    accent: '#f97316',
  },
  
  // Rose theme - elegant and romantic
  rose: {
    name: 'Rose',
    icon: '🌸',
    bg: 'bg-gradient-to-br from-pink-50 to-rose-100',
    chatBg: 'bg-pink-50/70',
    pattern: 'chat-pattern-hearts',
    ownMsg: 'bg-rose-500 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-pink-100',
    inputBg: 'bg-white',
    accent: '#f43f5e',
  },
  
  // Sky theme - bright and airy
  sky: {
    name: 'Sky',
    icon: '☁️',
    bg: 'bg-gradient-to-br from-cyan-50 to-sky-100',
    chatBg: 'bg-cyan-50/60',
    pattern: 'chat-pattern-clouds',
    ownMsg: 'bg-cyan-500 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-cyan-100',
    inputBg: 'bg-white',
    accent: '#06b6d4',
  },
  
  // Sand theme - earthy and natural
  sand: {
    name: 'Sand',
    icon: '🏖️',
    bg: 'bg-gradient-to-br from-amber-50 to-yellow-100',
    chatBg: 'bg-amber-50/70',
    pattern: 'chat-pattern-dots',
    ownMsg: 'bg-amber-600 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-amber-100',
    inputBg: 'bg-white',
    accent: '#d97706',
  },
  
  // Coral theme - vibrant and energetic
  coral: {
    name: 'Coral',
    icon: '🪸',
    bg: 'bg-gradient-to-br from-red-50 to-orange-100',
    chatBg: 'bg-red-50/60',
    pattern: 'chat-pattern-waves',
    ownMsg: 'bg-gradient-to-r from-red-400 to-orange-400 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-red-100',
    inputBg: 'bg-white',
    accent: '#ef4444',
  },
  
  // Sage theme - calm and grounded
  sage: {
    name: 'Sage',
    icon: '🌿',
    bg: 'bg-gradient-to-br from-green-50 to-lime-100',
    chatBg: 'bg-green-50/70',
    pattern: 'chat-pattern-leaves',
    ownMsg: 'bg-green-600 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-green-100',
    inputBg: 'bg-white',
    accent: '#16a34a',
  },
  
  // Glacier theme - cool and refreshing
  glacier: {
    name: 'Glacier',
    icon: '❄️',
    bg: 'bg-gradient-to-br from-slate-50 to-blue-100',
    chatBg: 'bg-slate-50/80',
    pattern: 'chat-pattern-grid',
    ownMsg: 'bg-slate-600 text-white',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-slate-200',
    inputBg: 'bg-white',
    accent: '#475569',
  },
  
  // Sunshine theme - happy and bright
  sunshine: {
    name: 'Sunshine',
    icon: '☀️',
    bg: 'bg-gradient-to-br from-yellow-50 to-orange-100',
    chatBg: 'bg-yellow-50/70',
    pattern: 'chat-pattern-stars',
    ownMsg: 'bg-yellow-500 text-grey-900',
    partnerMsg: 'bg-white text-grey-800 shadow-sm',
    headerBg: 'bg-white/90 backdrop-blur-lg border-b border-yellow-100',
    inputBg: 'bg-white',
    accent: '#eab308',
  },
};

// Theme Preview Component for the selector
const ThemePreview = ({ themeKey, theme, isSelected, onClick }) => (
  <motion.button
    onClick={onClick}
    className={`relative p-2 rounded-xl transition-all overflow-hidden ${
      isSelected ? 'ring-2 ring-offset-2 ring-cta' : 'hover:ring-2 hover:ring-grey-300'
    }`}
    whileHover={{ scale: 1.03 }}
    whileTap={{ scale: 0.97 }}
  >
    {/* Mini chat preview */}
    <div className={`w-20 h-24 rounded-lg ${theme.bg} overflow-hidden relative`}>
      {/* Pattern overlay */}
      <div className={`absolute inset-0 opacity-30 ${theme.pattern}`} />
      
      {/* Mini header */}
      <div className={`h-5 ${theme.headerBg} flex items-center px-1.5`}>
        <div className="w-2 h-2 rounded-full bg-grey-400" />
        <div className="ml-1 w-6 h-1.5 rounded bg-grey-300" />
      </div>
      
      {/* Mini chat area */}
      <div className={`p-1.5 ${theme.chatBg} flex-1 space-y-1`}>
        {/* Partner message */}
        <div className={`w-10 h-3 rounded-full ${theme.partnerMsg} ml-0`} />
        {/* Own message */}
        <div className={`w-12 h-3 rounded-full ${theme.ownMsg} ml-auto`} />
        {/* Partner message */}
        <div className={`w-8 h-3 rounded-full ${theme.partnerMsg} ml-0`} />
      </div>
      
      {/* Mini input */}
      <div className="absolute bottom-0 left-0 right-0 h-4 bg-white/80 flex items-center px-1">
        <div className={`flex-1 h-2 rounded-full ${theme.inputBg} border border-grey-200`} />
      </div>
    </div>
    
    {/* Theme name */}
    <div className="mt-1.5 text-center">
      <span className="text-sm">{theme.icon}</span>
      <p className="text-xs text-text-primary font-medium truncate">{theme.name}</p>
    </div>
    
    {/* Selected indicator */}
    {isSelected && (
      <motion.div 
        className="absolute top-1 right-1 w-4 h-4 bg-cta rounded-full flex items-center justify-center"
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
      >
        <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
        </svg>
      </motion.div>
    )}
  </motion.button>
);

export default function ChatRoom() {
  // ========================================================================
  // HOOKS & STATE
  // ========================================================================
  
  const { socket, isConnected } = useSocket();
  const router = useRouter();
  const { sessionId } = router.query;  // Extract sessionId from URL
  
  // Refs for DOM elements
  const chatContainerRef = useRef(null);  // For auto-scrolling
  const inputRef = useRef(null);           // For focusing input

  // Chat state
  const [messages, setMessages] = useState([]);           // Message history
  const [inputValue, setInputValue] = useState('');       // Current input text
  const [partnerInfo, setPartnerInfo] = useState(null);   // Partner details
  const [isPartnerTyping, setIsPartnerTyping] = useState(false);  // Typing indicator
  const [chatEnded, setChatEnded] = useState(false);      // Chat terminated flag
  
  // UI state
  const [showReportModal, setShowReportModal] = useState(false);    // Report dialog
  const [showThemeSelector, setShowThemeSelector] = useState(false); // Theme picker
  const [currentTheme, setCurrentTheme] = useState('classic');       // Active theme (default: classic)

  // Get current theme object
  const theme = chatThemes[currentTheme];

  // ========================================================================
  // AUTHENTICATION & SOCKET SETUP
  // ========================================================================

  /**
   * Effect: Initialize chat room on mount
   * - Verify user is logged in
   * - Load saved theme preference
   * - Register with socket server
   * - Set up event listeners for messages, typing, partner leaving
   */
  useEffect(() => {
    // Verify user is logged in
    const userData = getUserData();
    if (!userData) {
      router.push('/');  // Redirect to home if not authenticated
      return;
    }

    // Load saved theme preference from localStorage
    const savedTheme = localStorage.getItem('chatTheme');
    if (savedTheme && chatThemes[savedTheme]) {
      setCurrentTheme(savedTheme);
    }

    // Socket setup once sessionId is available
    if (socket && sessionId) {
      // Re-register user with server (maintains session after page refresh)
      socket.emit('auth:register', {
        deviceId: userData.deviceId,
        nickname: userData.nickname,
        bio: userData.bio,
        gender: userData.gender || 'unspecified',
      });

      // Listen for messages
      socket.on('chat:message', (message) => {
        setMessages((prev) => [...prev, message]);
      });

      // Listen for typing indicator
      socket.on('chat:typing', (data) => {
        setPartnerInfo((prev) => prev || { nickname: data.nickname });
        setIsPartnerTyping(true);
        setTimeout(() => setIsPartnerTyping(false), 2000);
      });

      // Listen for partner leaving
      socket.on('chat:partnerLeft', (data) => {
        setChatEnded(true);
        setMessages((prev) => [
          ...prev,
          { id: 'system-left', content: data.message, isSystem: true },
        ]);
      });

      return () => {
        socket.off('chat:message');
        socket.off('chat:typing');
        socket.off('chat:partnerLeft');
      };
    }
  }, [socket, sessionId]);

  // Auto-scroll to bottom
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [messages]);

  // Save theme preference
  const handleThemeChange = (themeName) => {
    setCurrentTheme(themeName);
    localStorage.setItem('chatTheme', themeName);
    setShowThemeSelector(false);
  };

  const handleSendMessage = (e) => {
    e.preventDefault();
    
    if (!inputValue.trim() || !socket || chatEnded) return;

    socket.emit('chat:send', { message: inputValue.trim() });
    setInputValue('');
    inputRef.current?.focus();
  };

  const handleTyping = () => {
    if (socket && !chatEnded) {
      socket.emit('chat:typing');
    }
  };

  const handleLeaveChat = () => {
    if (socket) {
      socket.emit('chat:leave');
    }
    router.push('/match');
  };

  const handleNextMatch = () => {
    if (socket) {
      socket.emit('chat:leave');
    }
    router.push('/match');
  };

  const handleReport = (reason) => {
    if (socket) {
      socket.emit('chat:report', { reason });
    }
    setShowReportModal(false);
    handleLeaveChat();
  };

  // Format timestamp
  const formatTime = (timestamp) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <div className={`min-h-screen ${theme.bg} flex flex-col relative overflow-hidden transition-colors duration-500`}>
      {/* Animated Background Elements */}
      {currentTheme === 'light' && (
        <>
          <motion.div 
            className="absolute top-[-20%] left-[-10%] w-[400px] h-[400px] bg-accent-green/20 rounded-full blur-3xl"
            animate={{ scale: [1, 1.2, 1], opacity: [0.2, 0.3, 0.2] }}
            transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
          />
          <motion.div 
            className="absolute bottom-[-20%] right-[-10%] w-[500px] h-[500px] bg-accent-blue/20 rounded-full blur-3xl"
            animate={{ scale: [1.2, 1, 1.2], opacity: [0.3, 0.4, 0.3] }}
            transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}
          />
        </>
      )}

      {/* Header */}
      <header className={`relative z-20 ${theme.headerBg} border-b border-white/20 px-4 lg:px-6 py-3 transition-colors duration-500`}>
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          <motion.div 
            className="flex items-center gap-3"
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
          >
            <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center shadow-soft border border-grey-100">
              <svg className="w-5 h-5 text-text-muted" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
              </svg>
            </div>
            <div>
              <p className="font-medium text-text-primary">
                {partnerInfo?.nickname || 'Stranger'}
              </p>
              <p className="text-xs text-text-muted">
                {chatEnded ? '🔴 Disconnected' : isPartnerTyping ? '✍️ Typing...' : '🟢 Online'}
              </p>
            </div>
          </motion.div>
          
          <div className="flex items-center gap-2">
            {/* Theme Selector Button */}
            <motion.button
              onClick={() => setShowThemeSelector(!showThemeSelector)}
              className="p-2.5 rounded-full bg-white text-text-muted hover:scale-105 transition-all border border-grey-100"
              whileTap={{ scale: 0.95 }}
              title="Change Theme"
            >
              <span className="text-lg">{theme.icon}</span>
            </motion.button>
            
            <motion.button
              onClick={() => setShowReportModal(true)}
              className="p-2.5 rounded-full bg-white text-text-muted hover:text-red-500 transition-all border border-grey-100"
              whileTap={{ scale: 0.95 }}
              title="Report"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
              </svg>
            </motion.button>
            
            <motion.button
              onClick={handleLeaveChat}
              className="p-2.5 rounded-full bg-white text-text-muted hover:text-text-primary transition-all border border-grey-100"
              whileTap={{ scale: 0.95 }}
              title="Leave Chat"
            >
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
              </svg>
            </motion.button>
          </div>
        </div>

        {/* Theme Selector Dropdown with Previews */}
        <AnimatePresence>
          {showThemeSelector && (
            <motion.div
              initial={{ opacity: 0, y: -10, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -10, scale: 0.95 }}
              className="absolute left-1/2 -translate-x-1/2 top-full mt-2 bg-white/95 backdrop-blur-xl rounded-2xl p-4 shadow-2xl z-50 border border-grey-100 max-w-[95vw] sm:max-w-lg"
            >
              <div className="flex items-center justify-between mb-3 px-1">
                <p className="text-sm text-text-primary font-semibold">Choose Theme</p>
                <button 
                  onClick={() => setShowThemeSelector(false)}
                  className="p-1 hover:bg-grey-100 rounded-full transition-colors"
                >
                  <svg className="w-4 h-4 text-text-muted" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
              <div className="grid grid-cols-4 sm:grid-cols-6 gap-2 max-h-[60vh] overflow-y-auto pr-1">
                {Object.entries(chatThemes).map(([key, t]) => (
                  <ThemePreview
                    key={key}
                    themeKey={key}
                    theme={t}
                    isSelected={currentTheme === key}
                    onClick={() => handleThemeChange(key)}
                  />
                ))}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </header>

      {/* Left Side Decoration - Hidden on mobile */}
      <div className="hidden xl:flex absolute left-6 top-1/2 -translate-y-1/2 z-10 flex-col gap-4">
        <motion.div
          className="glass px-4 py-3 rounded-card shadow-soft flex items-center"
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0, y: [0, -5, 0] }}
          transition={{ y: { duration: 3, repeat: Infinity, ease: "easeInOut" } }}
        >
          <svg className="w-5 h-5 text-violet-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
          <span className="text-text-primary font-medium text-sm ml-2">Live Chat</span>
        </motion.div>
        <motion.div
          className="glass px-4 py-3 rounded-card shadow-soft flex items-center"
          initial={{ opacity: 0, x: -30 }}
          animate={{ opacity: 1, x: 0, y: [0, 5, 0] }}
          transition={{ y: { duration: 4, repeat: Infinity, ease: "easeInOut", delay: 1 } }}
        >
          <svg className="w-5 h-5 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
          <span className="text-text-primary font-medium text-sm ml-2">End-to-End</span>
        </motion.div>
      </div>

      {/* Right Side Decoration - Hidden on mobile */}
      <div className="hidden xl:flex absolute right-6 top-1/2 -translate-y-1/2 z-10 flex-col gap-4">
        <motion.div
          className="glass px-4 py-3 rounded-card shadow-soft text-center"
          initial={{ opacity: 0, x: 30 }}
          animate={{ opacity: 1, x: 0 }}
        >
          <p className="text-2xl font-bold text-text-primary">{messages.length}</p>
          <p className="text-text-muted text-xs">Messages</p>
        </motion.div>
        <motion.div
          className="glass px-4 py-3 rounded-card shadow-soft flex items-center"
          initial={{ opacity: 0, x: 30 }}
          animate={{ opacity: 1, x: 0, y: [0, 5, 0] }}
          transition={{ y: { duration: 3.5, repeat: Infinity, ease: "easeInOut" } }}
        >
          <svg className="w-5 h-5 text-grey-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.228 9c.549-1.165 2.03-2 3.772-2 2.21 0 4 1.343 4 3 0 1.4-1.278 2.575-3.006 2.907-.542.104-.994.54-.994 1.093m0 3h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
          <span className="text-text-primary font-medium text-sm ml-2">Anonymous</span>
        </motion.div>
      </div>

      {/* Chat Messages Area */}
      <main 
        ref={chatContainerRef}
        className={`flex-1 overflow-y-auto p-4 lg:p-6 ${theme.chatBg} transition-colors duration-500 relative`}
      >
        {/* WhatsApp-style background pattern overlay */}
        <div className={`absolute inset-0 opacity-20 pointer-events-none ${theme.pattern || ''}`} />
        
        <div className="max-w-2xl mx-auto space-y-4 relative z-10">
          {/* System message at start */}
          <motion.div 
            className="text-center py-4"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
          >
            <p className="text-sm bg-white text-text-muted px-6 py-3 rounded-full inline-block shadow-soft">
              You're now chatting with a stranger. Say hi!
            </p>
          </motion.div>

          <AnimatePresence>
            {messages.map((message) => {
              // System message
              if (message.isSystem) {
                return (
                  <motion.div
                    key={message.id}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="text-center py-2"
                  >
                    <p className="text-sm text-text-muted">{message.content}</p>
                  </motion.div>
                );
              }

              // Regular message
              return (
                <motion.div
                  key={message.id}
                  {...(message.isOwn ? animations.ownMessage : animations.receivedMessage)}
                  className={`flex ${message.isOwn ? 'justify-end' : 'justify-start'}`}
                >
                  <motion.div
                    className={`max-w-[75%] rounded-2xl px-4 py-3 ${
                      message.isOwn
                        ? `${theme.ownMsg} rounded-br-md`
                        : `${theme.partnerMsg} rounded-bl-md`
                    }`}
                    whileHover={{ scale: 1.01 }}
                  >
                    <p className="break-words">{message.content}</p>
                    <p className={`text-xs mt-1 ${
                      message.isOwn 
                        ? 'text-white/70' 
                        : 'text-text-muted'
                    }`}>
                      {formatTime(message.timestamp)}
                    </p>
                  </motion.div>
                </motion.div>
              );
            })}
          </AnimatePresence>

          {/* Typing indicator */}
          <AnimatePresence>
            {isPartnerTyping && !chatEnded && (
              <motion.div 
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="flex justify-start"
              >
                <div className={`${theme.partnerMsg} rounded-2xl px-5 py-3`}>
                  <div className="flex gap-1.5">
                    <motion.span 
                      className="w-2 h-2 bg-text-muted rounded-full"
                      animate={{ y: [0, -5, 0] }}
                      transition={{ duration: 0.6, repeat: Infinity, delay: 0 }}
                    />
                    <motion.span 
                      className="w-2 h-2 bg-text-muted rounded-full"
                      animate={{ y: [0, -5, 0] }}
                      transition={{ duration: 0.6, repeat: Infinity, delay: 0.2 }}
                    />
                    <motion.span 
                      className="w-2 h-2 bg-text-muted rounded-full"
                      animate={{ y: [0, -5, 0] }}
                      transition={{ duration: 0.6, repeat: Infinity, delay: 0.4 }}
                    />
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>

      {/* Input Area */}
      <footer className={`relative z-20 ${theme.headerBg} border-t border-white/20 p-4 transition-colors duration-500`}>
        <div className="max-w-2xl mx-auto">
          {chatEnded ? (
            <motion.button
              onClick={handleNextMatch}
              className="w-full bg-cta text-white font-semibold py-4 px-6 rounded-pill shadow-cta flex items-center justify-center gap-2"
              whileHover={{ scale: 1.02, y: -2 }}
              whileTap={{ scale: 0.98 }}
            >
              <span>Find New Match</span>
              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 5l7 7m0 0l-7 7m7-7H3" />
              </svg>
            </motion.button>
          ) : (
            <form onSubmit={handleSendMessage} className="flex gap-3">
              <input
                ref={inputRef}
                type="text"
                value={inputValue}
                onChange={(e) => {
                  setInputValue(e.target.value);
                  handleTyping();
                }}
                placeholder="Type a message..."
                maxLength={appConfig.maxMessageLength}
                className={`flex-1 ${theme.inputBg} rounded-pill px-5 py-3.5 text-text-primary placeholder-text-muted focus:outline-none focus:ring-2 focus:ring-cta transition-all border border-grey-200`}
                autoFocus
              />
              <motion.button
                type="submit"
                disabled={!inputValue.trim()}
                className="bg-cta text-white p-3.5 rounded-full shadow-cta transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
              >
                <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
                </svg>
              </motion.button>
            </form>
          )}
        </div>
      </footer>

      {/* Report Modal */}
      <AnimatePresence>
        {showReportModal && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50"
            onClick={() => setShowReportModal(false)}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className="glass rounded-mobile p-6 w-full max-w-sm"
              onClick={(e) => e.stopPropagation()}
            >
              <h3 className="text-lg font-semibold text-text-primary mb-2">Report User</h3>
              <p className="text-text-muted text-sm mb-4">
                Why are you reporting this user?
              </p>
              <div className="space-y-2">
                {['Inappropriate content', 'Harassment', 'Spam', 'Other'].map((reason) => (
                  <motion.button
                    key={reason}
                    onClick={() => handleReport(reason)}
                    className="w-full text-left px-4 py-3 rounded-card bg-surface hover:bg-grey-200 text-text-primary transition-all flex items-center gap-3"
                    whileHover={{ x: 5 }}
                    whileTap={{ scale: 0.98 }}
                  >
                    <span className="text-red-500">⚠️</span>
                    {reason}
                  </motion.button>
                ))}
              </div>
              <motion.button
                onClick={() => setShowReportModal(false)}
                className="w-full mt-4 py-3 text-text-muted hover:text-text-primary transition-colors"
                whileTap={{ scale: 0.98 }}
              >
                Cancel
              </motion.button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

